

services:
  management-svc:
    container_name: mk-management-svc
    build:
      context: ./mitra-kirim-be-mgmt
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: config
    depends_on:
      - redis
      - postgres
  email-svc:
    container_name: mk-email-svc
    build:
      context: ./mitra-kirim-be-email
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    environment:
      REDIS_HOST: config
    depends_on:
      - redis
  postgres:
    container_name: mk-db
    image: postgres:latest
    environment:
      POSTGRES_DB: mitra_kirim
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5000:5000"
    volumes:
      - mk_volume:/var/lib/postrgresql/data
    command: -p 5000

  redis:
    container_name: mk-cache
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - mk_volume:/var/lib/config/data

volumes:
  mk_volume: {}
